@baseUrlProd = http://sieli-books.onrender.com/api
@baseUrlLocal = http://localhost:3500/api
@baseUrl = {{baseUrlLocal}}

{{baseUrl}}/version

###
{{baseUrl}}/books


###
{{baseUrl}}/books/6508640b67e63b4db8bf633d

###
POST {{baseUrl}}/books HTTP/1.1
Content-Type: application/json

{
  "title": "The subtil art of not giving a fuck",
  "author": "Mark Manson",
  "desc": "The description",
  "year": 2016
}

###
PATCH {{baseUrl}}/books/6508583db601bfc571d2116f HTTP/1.1
Content-Type: application/json

{
  "year": 2016
}

###
DELETE {{baseUrl}}/books/6508583db601bfc571d2116f HTTP/1.1


###
POST {{baseUrl}}/auth/tokens HTTP/1.1
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "53CR37P455"
}

